<?php
$rtbs_iframe_array = array(
    'address' => array(),
    'a' => array(
            'href' => true,
            'rel' => true,
            'rev' => true,
            'name' => true,
            'target' => true,
            'style' => true,
	        'class' => true,
	        'id' => true,
    ),
    'abbr' => array(),
    'acronym' => array(),
    'area' => array(
            'alt' => true,
            'coords' => true,
            'href' => true,
            'nohref' => true,
            'shape' => true,
            'target' => true,
    ),
    'article' => array(
            'align' => true,
            'dir' => true,
            'lang' => true,
            'xml:lang' => true,
	        'style' => true,
	        'class' => true,
	        'id' => true,
    ),
    'aside' => array(
            'align' => true,
            'dir' => true,
            'lang' => true,
            'xml:lang' => true,
	        'style' => true,
	        'class' => true,
	        'id' => true,
    ),
    'audio' => array(
            'autoplay' => true,
            'controls' => true,
            'loop' => true,
            'muted' => true,
            'preload' => true,
            'src' => true,
    	    'style' => true,
	        'class' => true,
	        'id' => true,
    ),
    'b' => array(),
    'big' => array(),
    'blockquote' => array(
            'cite' => true,
            'lang' => true,
            'xml:lang' => true,
	        'style' => true,
	        'class' => true,
	        'id' => true,
    ),
    'br' => array(),
    'button' => array(
            'disabled' => true,
            'name' => true,
            'type' => true,
            'value' => true,
	        'style' => true,
	        'class' => true,
	        'id' => true,
    ),
    'caption' => array(
            'align' => true,
    ),
    'cite' => array(
            'dir' => true,
            'lang' => true,
    ),
    'code' => array(),
    'col' => array(
            'align' => true,
            'char' => true,
            'charoff' => true,
            'span' => true,
            'dir' => true,
            'valign' => true,
            'width' => true,
    ),
    'colgroup' => array(
            'align' => true,
            'char' => true,
            'charoff' => true,
            'span' => true,
            'valign' => true,
            'width' => true,
    ),
    'del' => array(
            'datetime' => true,
    ),
    'dd' => array(),
    'dfn' => array(),
    'details' => array(
            'align' => true,
            'dir' => true,
            'lang' => true,
            'open' => true,
            'xml:lang' => true,
    ),
    'div' => array(
            'align' => true,
            'dir' => true,
	        'style' => true,
	        'class' => true,
	        'id' => true,
            'lang' => true,
            'xml:lang' => true,
    ),
    'dl' => array(),
    'dt' => array(),
    'em' => array(),
    'fieldset' => array(
	        'style' => true,
	        'class' => true,
	        'id' => true,
    ),
    'figure' => array(
            'align' => true,
            'dir' => true,
            'lang' => true,
            'xml:lang' => true,
    ),
    'figcaption' => array(
            'align' => true,
            'dir' => true,
            'lang' => true,
            'xml:lang' => true,
    ),
    'font' => array(
            'color' => true,
            'face' => true,
            'size' => true,
    ),
    'footer' => array(
            'align' => true,
            'dir' => true,
            'lang' => true,
            'xml:lang' => true,
	        'style' => true,
	        'class' => true,
	        'id' => true,
    ),
    'form' => array(
            'action' => true,
            'accept' => true,
            'accept-charset' => true,
            'enctype' => true,
            'method' => true,
            'name' => true,
            'target' => true,
	        'style' => true,
	        'class' => true,
	        'id' => true,
    ),
    'h1' => array(
            'align' => true,
    	       'style' => true,
	        'class' => true,
	        'id' => true,
    ),
    'h2' => array(
            'align' => true,
	        'style' => true,
	        'class' => true,
	        'id' => true,
    ),
    'h3' => array(
            'align' => true,
	        'style' => true,
	        'class' => true,
	        'id' => true,
    ),
    'h4' => array(
            'align' => true,
	        'style' => true,
	        'class' => true,
	        'id' => true,
    ),
    'h5' => array(
            'align' => true,
	        'style' => true,
	        'class' => true,
	        'id' => true,
    ),
    'h6' => array(
            'align' => true,
	        'style' => true,
	        'class' => true,
	        'id' => true,
    ),
    'header' => array(
            'align' => true,
            'dir' => true,
            'lang' => true,
            'xml:lang' => true,
    ),
    'hgroup' => array(
            'align' => true,
            'dir' => true,
            'lang' => true,
            'xml:lang' => true,
    ),
    'hr' => array(
            'align' => true,
            'noshade' => true,
            'size' => true,
            'width' => true,
    ),
    'i' => array(),
    'iframe' => array(
        'src'             => array(),
		'height'          => array(),
		'width'           => array(),
		'frameborder'     => array(),
		'allowfullscreen' => array(),
	    'style' => true,
	    'class' => true,
	    'id' => true,
    ),
    'img' => array(
            'alt' => true,
            'align' => true,
            'border' => true,
            'height' => true,
            'hspace' => true,
            'longdesc' => true,
            'vspace' => true,
            'src' => true,
            'usemap' => true,
            'width' => true,
	        'style' => true,
	        'class' => true,
	        'id' => true,
    ),
    'ins' => array(
            'datetime' => true,
            'cite' => true,
    ),
    'kbd' => array(),
    'label' => array(
            'for' => true,
	        'style' => true,
	        'class' => true,
	        'id' => true,
    ),
    'legend' => array(
            'align' => true,
    ),
    'li' => array(
            'align' => true,
            'value' => true,
	        'style' => true,
	        'class' => true,
	        'id' => true,
    ),
    'map' => array(
            'name' => true,
    ),
    'mark' => array(),
    'menu' => array(
            'type' => true,
    ),
    'nav' => array(
            'align' => true,
            'dir' => true,
            'lang' => true,
            'xml:lang' => true,
	        'style' => true,
	        'class' => true,
	        'id' => true,
    ),
    'p' => array(
            'align' => true,
            'dir' => true,
            'lang' => true,
            'xml:lang' => true,
	        'style' => true,
	        'class' => true,
	        'id' => true,
    ),
    'pre' => array(
            'width' => true,
    ),
    'q' => array(
            'cite' => true,
    ),
    's' => array(),
    'samp' => array(),
    'span' => array(
            'dir' => true,
            'align' => true,
            'lang' => true,
            'xml:lang' => true,
	        'style' => true,
	        'class' => true,
	        'id' => true,
    ),
    'section' => array(
            'align' => true,
            'dir' => true,
            'lang' => true,
            'xml:lang' => true,
	        'style' => true,
	        'class' => true,
	        'id' => true,
    ),
    'small' => array(),
    'strike' => array(),
    'strong' => array(),
    'sub' => array(),
    'summary' => array(
        'align' => true,
        'dir' => true,
            'lang' => true,
            'xml:lang' => true,
    ),
    'sup' => array(),
    'table' => array(
            'align' => true,
            'bgcolor' => true,
            'border' => true,
            'cellpadding' => true,
            'cellspacing' => true,
            'dir' => true,
            'rules' => true,
            'summary' => true,
            'width' => true,
	        'style' => true,
	        'class' => true,
	        'id' => true,
    ),
    'tbody' => array(
            'align' => true,
            'char' => true,
            'charoff' => true,
            'valign' => true,
	        'style' => true,
	        'class' => true,
	        'id' => true,
    ),
    'td' => array(
            'abbr' => true,
            'align' => true,
            'axis' => true,
            'bgcolor' => true,
            'char' => true,
            'charoff' => true,
            'colspan' => true,
            'dir' => true,
            'headers' => true,
            'height' => true,
            'nowrap' => true,
            'rowspan' => true,
            'scope' => true,
            'valign' => true,
            'width' => true,
	        'style' => true,
	        'class' => true,
	        'id' => true,
    ),
    'textarea' => array(
            'cols' => true,
            'rows' => true,
            'disabled' => true,
            'name' => true,
            'readonly' => true,
	        'style' => true,
	        'class' => true,
	        'id' => true,
    ),
    'tfoot' => array(
            'align' => true,
            'char' => true,
            'charoff' => true,
            'valign' => true,
	        'style' => true,
	        'class' => true,
	        'id' => true,
    ),
    'th' => array(
            'abbr' => true,
            'align' => true,
            'axis' => true,
            'bgcolor' => true,
            'char' => true,
            'charoff' => true,
            'colspan' => true,
            'headers' => true,
            'height' => true,
            'nowrap' => true,
            'rowspan' => true,
            'scope' => true,
            'valign' => true,
            'width' => true,
    	    'style' => true,
	        'class' => true,
	        'id' => true,v
    ),
    'thead' => array(
            'align' => true,
            'char' => true,
            'charoff' => true,
            'valign' => true,
	        'style' => true,
	        'class' => true,
	        'id' => true,
    ),
    'title' => array(),
    'tr' => array(
            'align' => true,
            'bgcolor' => true,
            'char' => true,
            'charoff' => true,
            'valign' => true,
	        'style' => true,
	        'class' => true,
	        'id' => true,
    ),
    'track' => array(
            'default' => true,
            'kind' => true,
            'label' => true,
            'src' => true,
            'srclang' => true,
    ),
    'tt' => array(),
    'u' => array(),
    'ul' => array(
            'type' => true,
	        'style' => true,
	        'class' => true,
	        'id' => true,
    ),
    'ol' => array(
            'start' => true,
            'type' => true,
	        'style' => true,
	        'class' => true,
	        'id' => true,
    ),
    'var' => array(),
    'video' => array(
            'autoplay' => true,
            'controls' => true,
            'height' => true,
            'loop' => true,
            'muted' => true,
            'poster' => true,
            'preload' => true,
            'src' => true,
            'width' => true,
	        'style' => true,
	        'class' => true,
	        'id' => true,
    )
)
?>
